name: Lint

on:
  push:
    paths:
      - '**.py'

  pull_request:
    paths:
      - '**.py'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install .[lint]
      - name: Lint
        run: |
          flake8 --ignore=E501,E261,W503 emod_api
